### ISSUE TITLE
📋 Open source checklist

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-platform#11]
In order to prep this repository for open source use and consumption, we need to complete this checklist:

- [x] Add .github directory with pull request template, issue template(s) (1 template for bugs, 1 template for features)
- [x] Add Reaction's standard LICENSE.md
- [x] Add Reaction's standard CODE_OF_CONDUCT.md
- [x] Add Reaction's standard CONTRIBUTING.md

## README checklist
- [x] Add a screenshot, if applicable
- [x] Add and check install instructions
- [x] Add requirements list
- [x] Add link back to reactioncommerce.com, Reaction repo, Reaction docs, and other related Reaction tools/repos
- [x] Make it clear in the README whether this repository is open to new features, or whether new feature requests should go into: https://github.com/reactioncommerce/reaction-feature-requests
